# DataSource配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  main:
    banner-mode: off # 关闭SpringBoot启动图标(banner)
# MybatisPlus日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false # 关闭MybatisPlus启动图标
    db-config:
      id-type: assign_id
      table-prefix: tbl_
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0